import sys
from unittest.mock import MagicMock

# Mock required packages for testing
class MockPackage(MagicMock):
    __path__ = []
    __spec__ = None

hivemind_modules = [
    "hivemind",
    "hivemind.moe",
    "hivemind.moe.client",
    "hivemind.moe.client.remote_expert_worker",
    "hivemind.moe.expert_uid",
    "hivemind.moe.server",
    "hivemind.moe.server.connection_handler",
    "hivemind.moe.server.module_backend",
    "hivemind.p2p",
    "hivemind.p2p.p2p_daemon",
    "hivemind.p2p.p2p_daemon_bindings",
    "hivemind.p2p.p2p_daemon_bindings.control",
    "hivemind.proto",
    "hivemind.utils",
    "hivemind.compression",
    "hivemind.compression.serialization",
    "hivemind.dht",
    "hivemind.dht.node",
    "hivemind.utils.logging",
    "hivemind.utils.mpfuture",
    "hivemind.utils.tensor_descr",
    "hivemind.utils.asyncio",
    "hivemind.utils.streaming",
    "hivemind.utils.nested",
    "hivemind.utils.custom_layers",
    "hivemind.optim",
    "hivemind.optim.fault_tolerance",
]
for mod in hivemind_modules:
    sys.modules[mod] = MockPackage()

sys.modules["tensor_parallel"] = MockPackage()
sys.modules["tensor_parallel.tensor_parallel"] = MockPackage()
sys.modules["tensor_parallel.slicing_configs"] = MockPackage()

import torch
import torch.nn as nn
from petals.client.ptune import PTuneMixin

class DummyConfig:
    tuning_mode = "deep_ptune"
    pre_seq_len = 5
    hidden_size = 16
    num_hidden_layers = 4

class DummyWordEmbeddings:
    weight = torch.zeros(1, dtype=torch.float32)

class PTuneMock(PTuneMixin, nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.word_embeddings = DummyWordEmbeddings()
        self.init_prompts(config)

def test_deep_ptune_shapes():
    config = DummyConfig()
    model = PTuneMock(config)

    batch_size = 2
    prompts, intermediate_prompts = model.get_prompt(batch_size=batch_size)

    # Check shapes
    assert prompts.shape == (batch_size, config.pre_seq_len, config.hidden_size)
    assert intermediate_prompts.shape == (config.num_hidden_layers, batch_size, config.pre_seq_len, config.hidden_size)

    # The first layer should be padded with zeros
    assert torch.all(intermediate_prompts[0] == 0).item()

    # The other layers should be generated by embeddings (which are randomly initialized)
    # They shouldn't be all zero, so checking their sum should be non-zero
    assert not torch.all(intermediate_prompts[1:] == 0).item()
